---
# tasks file for frontend
- name: Download frontend.tar.gz
  become: false
  get_url:
    url: "https://nexus.praktikum-services.tech/repository/std-033-68-frontend/{{ frontend_version }}/sausage-store-{{ frontend_version }}.tar.gz"
    dest: "/home/ansible/frontend-{{ frontend_version }}.tar.gz"
    mode: '0775'
    username: "std-033-68"
    password: "{{ nexus_pwd }}"

- name: Create www-data user
  user:
    name: "www-data"
    groups: ansible
    create_home: no
    shell: /sbin/nologin

- name: Create a frontend directory
  ansible.builtin.file:
    path: "{{ frontend_directory }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Extract frontend.tar.gz to frontend dir
  ansible.builtin.unarchive:
    src: "/home/ansible/frontend-{{ frontend_version }}.tar.gz"
    dest: "{{ frontend_directory }}"
    owner: www-data
    group: www-data
    mode: '0755'
    remote_src: yes
