---
# tasks file for prepare

- name: install jdk
  apt:
    update_cache: yes
    name: 'openjdk-16-jdk'
    state: present # желаемое состояние пакета, present (установка пакета)
  loop:
    - openjdk-16-jdk

- name: install python3 and pip
  apt:
    name: '{{ item }}'
    state: present
  loop:
    - python3
    - python3-pip

- name: install lxml
  pip:
    name: lxml
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: Install Nginx
  apt:
    name: nginx
    state: latest
    update_cache: yes
